### ISSUE TITLE
Confusion about Maybe and Option

### ISSUE THREAD

**Issue by xsveda** [arrow-kt/bow#44]
My iOS friends are about to try Bow but we are a little bit confused about naming of `Option`/`Maybe`.
Arrow for Kotlin is using `Option`, Bow is using `Maybe `and name Option is used for nullable types `T?`
`Maybe `is also in conflict with RxSwift's `Maybe`. 

What are the reasons for using `Maybe `instead of `Option `in Bow?

Thanks for any hint!

**Comment by truizlop** [comment]
Hi @xsveda, first of all, you need to be aware that the library might not be 100% ready for production usage and we are going to be making changes to it. Nonetheless, it is very valuable that you start using it and provide us feedback about bugs and usage difficulties that you may find.

Regarding your question, if you study the implementation of `Maybe`, you can see that internally it uses the native optional types `T?`. The main reason to use `Maybe` instead of native `Option` is that `Maybe` is implemented simulating a *Higher Kinded Type*. This way, the "container" can be abstracted away and you can create polymorphic programs. Swift does not support HKs natively yet; it is in the [Generics Manifesto](https://github.com/apple/swift/blob/master/docs/GenericsManifesto.md#higher-kinded-types) but still we don't know when they will get included in the language. The `Maybe` class provides methods to convert to/from native `Option`; therefore, you can use the native version if you prefer, and transform to `Maybe` in those cases you are in the need of a Higher Kind.

For further information on Higher Kinds, I suggest you read the docs for Arrow, where we have several explanations and examples. If you have additional questions, feel free to ask :)

**Comment by xsveda** [comment]
Hi @truizlop, thank you for such quick and exhaustive answer!
I was not aware that HKs are being considered for Swift, that's great. 
Regarding naming, if I understand it correctly, then the similar things in Arrow and Bow are named differently:

|   	|   Arrow	|  Bow |
|:-:	|:-:	|:-:	|
|   "Container" for `T`	|   Option	|   Maybe	|
|   Native `T?`	|   Nullable	|   Option	|

Is it correct? Isn't it confusing?

**Comment by truizlop** [comment]
It may be confusing. I chose `Maybe` because the native `T?` in Swift is called `Optional` internally (represented by an enum) and I thought it could be easier to distiguish from the native one. If you think it should be named `Option` as in Arrow, it is totally open for discussion and we can proceed to renaming it. But yes, you understood correctly, just a minor change in your table:


  | Arrow | Bow
-- | -- | --
"Container" for T | Option | Maybe
Native T? | Nullable | Optional

**Comment by truizlop** [comment]
Also, to make things a bit more complicated, there is a class in the Optics package that is called `Optional`; that's why I am still more inclined to call it `Maybe`.

**Comment by xsveda** [comment]
For the `Option`/`Optional` I ment it fro Bow's point of view when `Maybe` has methods like `fromOption`/`toOption`. 

I understand the effort to distiguifh from native `Optional`.
Here are my few reasons why I would name it `Option`:

1. `Arrow` and also other libs as `Scalaz` all use `Option`
2. `Arrow` works fine with Java when there is also an `Optional` in the language and in other commonly used libs as Guava
3. `Maybe` is well known and defined in the Rx world

**Comment by truizlop** [comment]
Thanks for your input. I will now proceed to discuss it with the rest of the organization (you can join the discussion on gitter) and let's try to make a decision regarding the rename.

**Comment by truizlop** [comment]
This has been addressed in #45.
